# Generated by Django 4.1.7 on 2023-03-10 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True)),
                ('img', models.ImageField(null=True, upload_to='images/types')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('price', models.FloatField(null=True)),
                ('img', models.ImageField(null=True, upload_to='images/%y/%m/%d')),
                ('description', models.CharField(max_length=4000, null=True)),
                ('on_stock', models.BooleanField(default=True)),
                ('left', models.IntegerField(null=True)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.type')),
            ],
        ),
    ]
