# Generated by Django 4.1.7 on 2023-03-10 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='img',
        ),
    ]
