# Generated by Django 4.1.7 on 2023-03-14 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_buying_delete_buyings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buying',
            name='paymentMethod',
        ),
    ]
