# Generated by Django 4.1.7 on 2023-03-14 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_buying_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='buying',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 14, 9, 8, 13, 358188, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
