# Generated by Django 4.1.7 on 2023-03-16 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_buying_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buying',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='buying',
            name='being_delivered',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='buying',
            name='is_delivered',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='buying',
            name='serial_key',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='buying',
            name='date',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
    ]
